name: Packer

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of ami to build'
        required: true
        default: 'amazon'

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: "templates/aws/${{ github.event.inputs.name }}"

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: "templates/aws/${{ github.event.inputs.name }}"

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: "templates/aws/${{ github.event.inputs.name }}"
        env:
          PACKER_LOG: 1

      # Need to publish the artifacts...
